### ISSUE TITLE
inliner compression and pre leads to strangeness

### ISSUE THREAD

**Issue by Herst** [remy/inliner#117]
Inputting the following into `inliner` 1.9.5 without `-n`:

``` html
<!DOCTYPE html>
<html>
<head><title>test</title></head>
<body>

<pre><p class="foo">bar</p></pre>

</body>
</html>
```

becomes:

``` html
<!DOCTYPE html> <html> <head><title>test</title></head> <body> <pre><p class="foo">bar<p></p></p class="foo"></pre> </body> </html>
```

Especially note the closing tag with the nonsensical class attribute: `</p class="foo">`

**Comment by remy** [comment]
The source HTML is invalid which is why it's coming out corrupted.

[Source](https://gist.github.com/remy/53c384a44e8cfad7e6a8517d5978be16) and [validation fail](https://validator.w3.org/nu/?doc=https%3A%2F%2Fcdn.rawgit.com%2Fremy%2F53c384a44e8cfad7e6a8517d5978be16%2Fraw%2Fd531f67495180471b762a90cb431dc80a87761e5%2F117-inliner-issue.html)
